# Generated by Django 5.0.7 on 2024-09-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('student', 'position'), name='unique_vote_per_position'),
        ),
    ]
