# Generated by Django 5.0.7 on 2024-09-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_student_is_active_student_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
