# Generated by Django 5.0.7 on 2024-10-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_student_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contestant_images/'),
        ),
    ]
