# Generated by Django 5.0.7 on 2024-10-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_contestant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='image',
            field=models.ImageField(default='default-contestant.jpg', upload_to='contestants/'),
        ),
    ]
