# Generated by Django 5.2.4 on 2025-08-07 07:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_contestant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='contestants'),
        ),
    ]
