# Generated by Django 4.2.7 on 2025-09-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_contestant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='importance',
            field=models.PositiveIntegerField(choices=[(1, '1 - Very High'), (2, '2 - High'), (3, '3'), (4, '4'), (5, '5 - Medium'), (6, '6'), (7, '7'), (8, '8 - Low'), (9, '9 - Very Low'), (10, '10 - Lowest')]),
        ),
    ]
