# Generated by Django 4.2.7 on 2025-09-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_position_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='importance',
            field=models.PositiveIntegerField(choices=[(1, '1 - Very High'), (2, '2 - High'), (3, '3'), (4, '4'), (5, '5 - Medium'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10 - Low'), (11, '11 - Very Low'), (12, '9 - Lowest')]),
        ),
    ]
